---
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.7
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            make test
            bash <(curl -s https://codecov.io/bash)
