---
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/go:1.19.4
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: |
            make test
            bash <(curl -s https://codecov.io/bash)
